### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by leehambley** [jrochkind/cap_git_tools#1]
Hi @jrochkind,

Ever thought that these might be suitable for upstream inclusion in Capistrano? They add a lot of value, and I would love to pull them; I'm using something almost the same myself day to day.
- Lee

**Comment by jrochkind** [comment]
@leehambley Sure, I'd be thrilled if they were included in Capistrano, including someone else sharing the maintenance burden. :)  Note at the moment the code may not be entirely mature though, haven't tested them on any other systems than my own yet (there are probably some edge case and different-env bugs waiting), and they lack automated tests (some testing env support is obviously required; I thought of some ways to create automated tests for em, but was too lazy to actually do it). 

There were also a couple other 'fancy' features that I had intended for parity with `gitflow`, but hadn't gotten to yet (and may never, I am not sure I would need/use htem myself personally). 

But if you're interested despite all that, you're definitely welcome to take the code, just let me know if you have so I can point people there instead. 

But as long as I have your attention, you know what I'd _really_ like to see part of capistrano?  Just some documentation I wrote, documenting my own struggle to figure out how to use Cap with rails!  Would you mind if I add this to the Cap wiki?  https://gist.github.com/2171913

**Comment by leehambley** [comment]
> But as long as I have your attention, you know what I'd really like to see part of capistrano? Just some documentation I wrote, documenting my own struggle to figure out how to use Cap with rails! Would you mind if I add this to the Cap wiki? https://gist.github.com/2171913

Just some information for you, there's a (slow) work in progress to replace Capistrano with a sane rewrite, you can follow the work at https://github.com/deployrb/deploy.

By popular request, I've started a capistranorb repository at https://github.com/capistrano/capistranorb.com which I'm planning to move the "getting started" guide and FAQs into.

I want to move away from the wiki style (I can't track ANYTHING that happens there!) - and pull-request some open soruce documentation that's hosted at Heroku.

Note, the deployrb project will probably stay as a general purpose "do stuff on those hosts" toolkit, and a more "railsesque" wrapper layer consistent with current conventions will exist as Capistrano v3. backed by deployrb.

I'll keep in touch regarding bringing some of this stuff up-stream (I know what a nightmare testing can be) - but I would like to at least re-factor a little to ensure that it's compatible with the other scm modules where the same paradigms apply.

**Comment by jrochkind** [comment]
Cool, I'm probably not going to have time/interest to refactor this code to be even more general purpose and make a pull request myself -- but you're more than welcome to take it and do whatever you like it with it, let's say it's MIT-license licensed. 

Yeah, there's the 'other scm' issue, which I think could be actually quite complicated -- the main hard part about this code was figuring out how to interact with git the right way, which git being git requires shell-out screen-scraping.  (and that's the place I'd guess there might still be some bugs hiding).  I could see doing this again for 4 or 5 other scm's being quite time consuming.  

There's also a couple of places in the code that the integration with cap is kind of hacky, I just figured out the 'right' way to do it as best as I could, but you could probably do better. 

On the other hand, the _docs_ -- I'd love to contribute my guide docs to some official place -- would you look kindly on a pull request to capistranorb repo based on my guide?  (I hadn't been aware of that capistranorb repo, thanks. Suggest that maybe the docs should self-referentially point out capistranorb repo, so people know where to send doc pull requests to).  I really love Cap now that I have figured it out (I wrote this stuff in part as an exersize to become familiar with it's inner workings) -- but figuring it out, and just getting started using it for a Rails app, was more time consuming for me than I think it could be with the right kind of docs, so that guide was my attempt at that. 

As far as the rewrite of Cap -- I noticed you mention that somewhere else already -- I have to admit it fills me with a bit of fear, I just spent a bunch of time figuring out how cap works already, as well as writing custom tasks to suit my own workflows, and finally got familiar enough to be comfortable with it -- I hope I don't have to start over and rewrite all my tasks for the new version.  I also, once I understood it,  actually rather _like_ the current cap 2.x internal 'api', with it's rake-like tasks and the way that cap 'variables' work, etc.

**Comment by leehambley** [comment]
> On the other hand, the docs -- I'd love to contribute my guide docs to some official place -- would you look kindly on a pull request to capistranorb repo based on my guide? (I hadn't been aware of that capistranorb repo, thanks. Suggest that maybe the docs should self-referentially point out capistranorb repo, so people know where to send doc pull requests to). I really love Cap now that I have figured it out (I wrote this stuff in part as an exersize to become familiar with it's inner workings) -- but figuring it out, and just getting started using it for a Rails app, was more time consuming for me than I think it could be with the right kind of docs, so that guide was my attempt at that.

I'd absolutely love that, you are perfectly placed to write that with your current experience level and level of motivation. That repository has only existed since the weekend, a response to a nagging feeling I've had for a long time that GH Wikis are a useless tool for documenting.

There's also the "capistrano handbook" - something I haven't touched in years that I started to write before recognising that I was going down the rabbit hole, trying to write the ultimate guide to deployment; I'm happy that although I never finished it, it offered some value to people. The capistranorb.com repository is also a reaction to feeling guilty for never finishing my handbook.

> As far as the rewrite of Cap -- I noticed you mention that somewhere else already -- I have to admit it fills me with a bit of fear, I just spent a bunch of time figuring out how cap works already, as well as writing custom tasks to suit my own workflows, and finally got familiar enough to be comfortable with it.

It's natuarlly something to be fearful of, it's very possible that people who are lazy about upgrading will suffer. There'll be plenty of release announcements between now and then, an upgrade path of sorts, and you won't have to worry about it until at least the end of the year, I would guess. If and when the time comes, we'll encourage people to lock the Gem dependency at `~> 2.x.x`, until they can upgrade.

> I hope I don't have to start over and rewrite all my tasks for the new version. I also, once I understood it, actually rather like the current cap 2.x internal 'api', with it's rake-like tasks and the way that cap 'variables' work, etc.

We'll be shipping _much_ more of the common use-cases, and we'll try to take over a lot of the integrations with Bundler, rbenv, rvm, Hoptoad (is it Airbrake?) and more. The similarity to the Rake DSL is actually one of Cap's biggest liabilities, it's similar enough to be dangerous, as overriding tasks doesn't work as it does in rake (in rake they append to the task definition!) and some other minor nuisances.

I have a similar fear, "what about the books?!" and all the blog posts, and the rails guides, and the blah blah blah!! But as the Cap maintainer I've gotten a good feeling for what's wrong with Cap, and what needs to happen to make it easier to work with; in the end there's a lot of code for "doing programmable things in ruby over ssh on groups of servers" which could use a common framework; deploying is just one of them (Capistrano), Chef and puppet are others, as well as distributed shells (also a part of Cap, but I don't like that bit of code)

Unfortunately some of the things that are wrong are fundamentally broken, and there's no real path to fixing them (no real way to run rolling restarts, for example) and no way to test deploy recipes (not really), and the callback structure doesn't offer enough hooks to be truly universal, also the DSL makes writing API documentation a nightmare!

**Comment by jrochkind** [comment]
Cool, thanks.

I strongly approve of Cap taking over (and documenting) more of the  
more common Rails/Rack deploy tasks, awesome.

I get what you're saying about how Cap _could_ be a much more general- 
purpose tool. On the other hand, with greater abstraction often comes  
greater difficulty in making things really easy for newbies doing  
common use cases.  Cap already _is_ (not 'could be') super useful for  
Rack/Rails use cases -- but the current docs (and code's) attempt to  
remain agnostic about everything and not present itself as a Rails/ 
Rack tool is, IMO, part of what makes the learning/getting-started  
curve way steeper than it could be for newbies.  And with Rails 3.1+,  
including asset pipeline and bundler, I think even Rails newbies  
basically _have_ to use Cap if they want a non-painful deploy process  
(it's become just too painful without it), so difficulty in getting  
started with cap basically means difficulty with getting started  
deploying Rails apps.

But if I understand you right, and you're going to split cap into an  
abstract agnostic 'core' and a Rails (and/or ruby/rack) specific layer  
on top, where the ruby/rack specific layer then has to have no shame  
about providing for and documenting exactly what you need to do for a  
rails/ruby/rack deploy --- that does sound like a pretty good way to go.

It also sounds like a lot of work.  :) Making things more abstract and  
general-purpose while still being clean, easy to understand as a  
developer, and easy to use -- is always tricky. Good luck. Cap is  
super useful as it is already (And 2.x is way better than 1.x), thanks  
to all authors.

**Comment by leehambley** [comment]
> And with Rails 3.1+,
> including asset pipeline and bundler, I think even Rails newbies
> basically _have_ to use Cap if they want a non-painful deploy process
> (it's become just too painful without it), so difficulty in getting
> started with cap basically means difficulty with getting started
> deploying Rails apps.

Absolutely, I always expect someone to make Capistrano obsolete, but it's getting more and more difficult to just throw code on a server, and expect it to work!

> But if I understand you right, and you're going to split cap into an
> abstract agnostic 'core' and a Rails (and/or ruby/rack) specific layer
> on top, where the ruby/rack specific layer then has to have no shame
> about providing for and documenting exactly what you need to do for a
> rails/ruby/rack deploy --- that does sound like a pretty good way to go.

Deploy.rb will be a general framework (as I wrote) for doing things on hosts, the architypal usecase might look like this:

``` ruby
# Task to write-enable the cache on two servers which
# are having problems
on %{user@example.com user@example.com}[, in: :parallel ] do
  in "/opt/sites/example.com" do
    run "chmod go+w -R tmp/cache", as: :root
  end
end
```

That's more or less where we expect deploy.rb to begin, and end (more helpers for parallel or serial execution), more options with `with()` (environment) and some other general niceties.

Pretty much everything else is too tied to Capistrano; we're discussing right now where to put the "suites" - and how that should look, we really haven't made any decisions yet, whatever a "suite" becomes, that'll be responsible for hooks, defaults, callbacks, and everything the Cap DSL already does.

**Comment by jrochkind** [comment]
Perhaps one of the suites could actually be backwards-compat to Cap  
2.x, _but_ with built-in support for common Rails deploy tasks too!

(In general, in the ruby/rails open source eco-system, I've been  
getting frustrated about how non-backwards-compat everything is. It's  
gotten to the point where I often feel like I'm spending more time  
updating my code to work with the latest dependencies than I spend  
actually writing any new features, which is not joyful.)

**Comment by leehambley** [comment]
> (In general, in the ruby/rails open source eco-system, I've been
> getting frustrated about how non-backwards-compat everything is. It's
> gotten to the point where I often feel like I'm spending more time
> updating my code to work with the latest dependencies than I spend
> actually writing any new features, which is not joyful.)

I hear you, at least the core framework providers should take more care, the tools that work with other tools, (Paperclip, I'm looking at you and Rails). But sometimes tools do need a clean break, that said - the Cap API is so similar to rake, that running them in a rake context with a few sprinkles of sugar (`set()`, `fetch()`, `before()`, etc) might be close enough!

**Comment by jrochkind** [comment]
Ah, but everyone thinks _their_ tool is the one that justifiably needs  
a clean break to be it's best, while everyone _elses_ tool doesn't pay  
enough attention to backwards compat. :)  To me, Cap is an example of  
a core tool used by so many people that it ought to care about  
backwards compat.

But yeah, there's a fundamental tension between making things 'right'  
with what you've learned from the last iteration, being innovative --  
and being backwards compat. It's a tricky balance no matter what.

I suspect that if Cap 3.x does not support a backwards compat 'suite',  
then rejiggering everyting to use Rake would in fact not be any less  
work than just rejiggering everything to use Cap 3.x. It _looks_ like  
Rake, but it's enough Not Rake that if you have complex recipes using  
dependencies, there are going to be enough tricks involved to make it  
not worth it (and if you have only a very simple recipe, it won't be  
hard to migrate it anyway, presumably).

Of course, one could always just lock to ~> 2.x as you recommend too  
(thanks for using semver or at least semver-ish!). Be careful, if the  
migration pain is not low enough, you might find substantial portions  
of the community not following you, at least for a while.   (Oh, note  
in gemspec/gemfile you actually have to do "~> 2.x" or [">= 2.x.y", "<  
3.0.0"] to lock the right way. If you actually do "~> 2.x.y", you'll  
have locked to only 2.x and not 2.x+1 .)

Anyhow, thanks for the dialog, appreciate it.

**Comment by leehambley** [comment]
> Ah, but everyone thinks _their_ tool is the one that justifiably needs
> a clean break to be it's best, while everyone _elses_ tool doesn't pay
> enough attention to backwards compat. :)  To me, Cap is an example of
> a core tool used by so many people that it ought to care about
> backwards compat.

Haha, absolutely agree - I at least still feel a bit shell-shocked, here I am maintaining one of the most widely used tools, with almost no help, working as as freelancer in Europe… and there's scores of people queueing up to work on Rails for the accolades; yet I work on Cap alone mostly unable to drum up any kind of community consensus.

> Anyhow, thanks for the dialog, appreciate it.

Likewise, I've really enjoyed our exchange, I'd love to pick up with you on the https://github.com/capistrano/capistranorb.com repository, and start pushing the docs there a little.

**Comment by jrochkind** [comment]
> Haha, absolutely agree - I at least still feel a bit shell-shocked,  
> here I am maintaining one of the most widely used tools, with almost  
> no help, working as as freelancer in Europe… and there's scores of  
> people queueing up to work on Rails for the accolades; yet I work on  
> Cap alone mostly unable to drum up any kind of community consensus.

Ha, such is open source.

I think the role of project leader to some extent is to make the  
decisions based on a strategic vision, not wait for the consensus --  
esp when waiting for the consensus isn't working.  Of course, that has  
to be done trying to take account of what decisions will result in a  
tool that people will use and hopefully contribute to (keeping it easy  
to use, easy to understand the code to contribute to it, easy to  
migrate to new versions :) Plus good docs.).

If it were me in charge of cap, _especially_ taking account of limited  
developer resources, I would not be trying to abstract/generalize it,  
I'd be _focusing_ on the app deploy scenario/use case, with ruby/rack/ 
rails being the central supported environment (which if I understand  
right is where currently existing cap is _actually_ popular), and  
making it as good as possible for that.  In my experience, it's way  
harder and takes way more time (and has way more risk of turning into  
a giant pile of over-engineered spaghetti), the more abstract/general  
purpose you try to make something. Of course, there are pro's and  
con's, in theory if the abstraction/generalization goes _well_, you  
open it up to more users and potentially more contributors. But that's  
what I'd do if it were me. (Of course, you've also got to do what you  
find fun, or why would you be doing it, since you're not getting paid,  
heh).

It's possible to be too abstract or not abstract enough, but in ruby- 
land I think the 'over-engineered too abstract' is often the mistake  
made.

It's interesting to compare puppet/cap, as you started to. Because,  
yeah, they're both similar from a certain point of view, in that they  
both do operations on remote machines  -- the difference is largely in  
the use case focused on by the developers, the sweet spot. You  
probably _could_ use Puppet to deploy apps, but it'd be a mess. You  
probably -could- use Cap to do what puppet does, but it'd be a mess.  
Yeah, either tool _could_, in theory anyway, be abstracted to be just  
as good as the other one at it's use cases -- but it's _hard_ and time  
consuming and might fail.  People's needs are diverse and flexible  
enough that even limiting to a specific domain, it's _still_ hard to  
create something flexible enough to meet everyone's needs while still  
being nice and neat -- once you try to generalize your domain even  
more, it gets even harder. You _can_ make dinner with a swiss army  
knife, but it's a lot easier if you have a proper chef's knife and a  
proper paring knife, etc, and that'd probably remain true no matter  
how much time the Swiss Army Knife people spend trying to make a swiss  
army knife great for cooking dinner.   (Of course, yeah, all their  
blades might be forged in the same blade factory. The analogy is  
wearing thin.)

**Comment by jrochkind** [comment]
If you are still interested in pulling this into upstream Cap, I am not opposed to it, we can talk more. Or it might make sense to leave it as a seperate thing with it's own release schedule, I dunno. But it's got an open source license, of course nothing stopping you from pulling it now!

**Comment by leehambley** [comment]
Cheers @jrochkind ! (We're focusing on a fairly major rewrite of Cap to correspond with Rails 4, you might want to check out the v3 branch, the README doesn't quite do it justice at the moment, but there's some really good stuff in there)
